setopt no_global_rcs
if [[ -v __ZSHENV_SOURCED ]]; then return; fi
export __ZSHENV_SOURCED=1

[[ -f ~/.nix-profile/etc/profile.d/hm-session-vars.sh ]] && source ~/.nix-profile/etc/profile.d/hm-session-vars.sh
