# TODO:
# - surround_replace/add/delete (https://docs.helix-editor.com/surround.html)
# - align_view_center
# - kill_to_line_start, "Delete till start of line
# - kill_to_line_end, "Delete till end of line"
# - file_explorer
# - flip_selections
#
# missing features:
# - fuzzy find in current file -> implemented in my own fork
# - window/buffer management, eg stack

theme = "nordfox"

[editor]
scrolloff = 8
mouse = false
indent-guides.render = true
gutters = ["diagnostics", "spacer", "diff"]
completion-trigger-len = 4
auto-completion = false
auto-pairs = false
auto-info = false
jump-label-alphabet = "ntseriufhdywoa"
# bufferline = "always"

[editor.auto-save]
focus-lost = true

[editor.auto-save.after-delay]
enable = true

[editor.lsp]
display-inlay-hints = false
# noisy but useful logs
display-progress-messages = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.statusline]
left = ["mode", "spinner", "file-base-name", "read-only-indicator"]
right = [
    "diagnostics",
    "workspace-diagnostics",
    "file-type",
    "position",
    "position-percentage",
]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"
diagnostics = ["warning", "error"]
workspace-diagnostics = ["warning", "error"]

# too jumpy/noisy
# [editor.inline-diagnostics]
# cursor-line = "warning"

[keys.normal]

"n" = "move_char_left"
"e" = "move_line_down"
"i" = "move_char_right"
"u" = "move_line_up"
"up" = "scroll_up"
"down" = "scroll_down"

# Word movement
"l" = "move_prev_word_start"
"y" = "move_next_word_start"
"C-l" = "move_prev_long_word_start"
"C-y" = "move_next_long_word_end"

"k" = "page_up"
"h" = "page_down"

"<" = "jump_backward"
">" = "jump_forward"
"%" = "match_brackets"

"C-w" = "undo"
"C-f" = "redo"

# changes
"J" = "join_selections"
"x" = "delete_char_forward"
"v" = "select_mode"
"o" = "no_op"               # TODO use?

# search
"N" = "search_prev"
"E" = "search_next"

"C-d" = ":wqa"

[keys.normal.space]
"l" = "move_prev_word_end"       # <space>l: prev word end (ge)
"y" = "move_next_word_end"       # <space>y: next word end (e)
"n" = "goto_first_nonwhitespace" # <space>n: first non-ws in line (0^)
"i" = "goto_line_end"            # <space>i: end of line ($)
"u" = "goto_file_start"          # <space>u: top of file (gg)
"e" = "goto_file_end"            # <space>e: end of file (G)
"k" = "half_page_up"             # <space>k: half page up (C-u)
"h" = "half_page_down"           # <space>h: half page down (C-d)
"r" = "replace"                  # <space>r: replace single char
"," = "goto_last_modification"   # go to last insert
" " = "goto_word"                # hop equivalent

[keys.normal.'=']
"=" = ":format"

[keys.normal.g]
"e" = "goto_next_change"
"u" = "goto_prev_change"

# paste
[keys.normal.p]
"u" = "paste_clipboard_before"
"e" = "paste_clipboard_after"
"n" = "paste_clipboard_before" # TODO before
"i" = "paste_clipboard_after"  # TODO after

# insert commands
[keys.normal.s]
"n" = "insert_mode"
"i" = "append_mode"
"o" = "insert_at_line_end"
"m" = ["goto_first_nonwhitespace", "insert_mode"]
"u" = "open_above"
"e" = "open_below"
# "." = "replace"

[keys.normal.z]
"n" = "unindent"
"i" = "indent"

[keys.normal.f]
"f" = "buffer_search" # TODO fuzzy find in buffer na: filter manually with '%p ctrl-r %'
"n" = "rsearch"
"i" = "search"
# "," = "search_next"

[keys.normal.w]
"w" = "vsplit"
"u" = "jump_view_left"
"e" = "jump_view_right"
# "U" = "jump_view_up"
# "E" = "jump_view_down"
"," = "wclose"
"d" = "wclose"
"." = "wonly"

[keys.normal.t]
"t" = "goto_definition"
"r" = "goto_reference"
"n" = "file_picker"
"g" = "global_search"
"b" = "buffer_picker"
"e" = "symbol_picker"
"u" = "workspace_symbol_picker"
"j" = "jumplist_picker"
"." = "last_picker"
"c" = "changed_file_picker"     # TODO tc: diff to main -> here changed

[keys.normal.t.d]
"d" = "goto_next_diag"               # TODO should wrap
"e" = "diagnostics_picker"
"u" = "workspace_diagnostics_picker"

[keys.normal.a]
"." = "hover"
";" = "code_action"
"o" = "rename_symbol"
"h" = ":toggle lsp.display-inlay-hints"
"," = ":toggle end-of-line-diagnostics 'hint' 'disable'"
"=" = "select_references_to_symbol_under_cursor"

[keys.normal.","]
"c" = "toggle_comments"
# TODO :run-shell-command

# == Visual / Select mode entry ==
# In helix, v enters select mode; motions then extend the selection.
# This mimics pretty close to what we have been using in nvim lately.
# TODO to keep vn as select line (used a lot) move left/right is m/o
# TODO select word under cursor is useful, but now clashes with up/down
[keys.select]

# TODO where do we bind them?
"i" = "@miw"
# "u" = "@miW"
# "p" = "@mip"

"(" = "@mi("
")" = "@ma("
"{" = "@mi{"
"}" = "@ma}"
"[" = "@mi["
"]" = "@ma["
# "<" = "@mi<"
# ">" = "@ma>"
'"' = '@mi"'
"'" = "@mi'"
"`" = "@mi`"

# TODO
"o" = "extend_char_right"
"m" = "extend_char_left"
"e" = "extend_visual_line_down"
"u" = "extend_visual_line_up"
"n" = "extend_to_line_bounds"
"l" = "extend_prev_word_start"  # TODO vs long_word
"y" = "extend_next_word_start"
"k" = "page_up"
"h" = "page_down"

"v" = "exit_select_mode"

"r" = "change_selection"
"d" = "delete_selection"                        # TODO what is _noyank"?
"J" = "join_selections"
"c" = "yank_to_clipboard"
"x" = ["yank_to_clipboard", "delete_selection"] # TODO just delete_selection?
"p" = "replace_with_yanked"
F11 = "save_selection"                          # to jump list

"U" = "switch_to_uppercase"
"E" = "switch_to_lowercase"

[keys.select.space]
# TODO
"l" = "extend_prev_word_end"
"y" = "extend_next_word_end"
"k" = "half_page_up"
"h" = "half_page_down"
"i" = "extend_to_line_end"
"n" = "extend_to_line_start"
#
"e" = "@maw"
"u" = "@maW"
"p" = "@map"
'"' = '@ma"'
"'" = "@ma'"
"`" = "@ma`"


# treesitter
[keys.select.t]
"u" = ["expand_selection"]
"e" = ["shrink_selection"]

[keys.select.z]
"n" = ["unindent", "select_mode"]
"i" = ["indent", "select_mode"]

[keys.select.","]
"c" = "toggle_comments"

[keys.insert]
"C-d" = ["normal_mode", ":wqa"]
"C-t" = "completion"
F11 = "signature_help"          # TODO does not work?
